### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pquentin**
A few typos I noticed when reading this awesome PEP.

Would you accept another PR that uses only "naked" or "plain", but not both?

### CODE REVIEW

**Comment by gvanrossum** [comment]
OT: I’m curious, was this project mentioned somewhere public recently?

**Comment by pquentin** [comment]
Yes, in the Trio Gitter channel a few days ago, and then again today: https://gitter.im/python-trio/general. Many Trio users are excited by the progress you're making here

**Review by iritkatriel — APPROVED** [review]
Thanks!

**Comment by iritkatriel** [comment]
> Would you accept another PR that uses only "naked" or "plain", but not both?

Thanks, I'll get rid of most of the "plain"s but we can't use naked before it's defined.

**Pull request merged**
